var menulinks = new Array();

menulinks[1] = "<a href='index.php?_m=core&_a=dashboard' title='Dashboard'>Dashboard</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='#' title='Preferences'id='linkdpreferences' onClick=\"javascript:CustomPopup('dpreferences', event, \'linkdpreferences\', \'dpreferences\');this.blur();\" onMouseUp=\"this.blur();\">Preferences&nbsp;<img src='https://support.bytro.com/themes/admin_default/menudrop.gif' border='0' /></a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='index.php?_m=core&_a=privatemessages' title='Private Messages'>Private Messages</a>";
menulinks[2] = "<a href='index.php?_m=tickets&_a=manage' title='Manage Tickets'>Manage Tickets</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='#' title='Search'id='linkticketsearch' onClick=\"javascript:CustomPopup('ticketsearch', event, \'linkticketsearch\', \'ticketsearch\');this.blur();\" onMouseUp=\"this.blur();\">Search&nbsp;<img src='https://support.bytro.com/themes/admin_default/menudrop.gif' border='0' /></a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='#' title='Predefined Replies'id='linkticketpred' onClick=\"javascript:CustomPopup('ticketpred', event, \'linkticketpred\', \'ticketpred\');this.blur();\" onMouseUp=\"this.blur();\">Predefined Replies&nbsp;<img src='https://support.bytro.com/themes/admin_default/menudrop.gif' border='0' /></a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='#' title='Alerts'id='linkticketalerts' onClick=\"javascript:CustomPopup('ticketalerts', event, \'linkticketalerts\', \'ticketalerts\');this.blur();\" onMouseUp=\"this.blur();\">Alerts&nbsp;<img src='https://support.bytro.com/themes/admin_default/menudrop.gif' border='0' /></a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='#' title='Filters'id='linkticketfilters' onClick=\"javascript:CustomPopup('ticketfilters', event, \'linkticketfilters\', \'ticketfilters\');this.blur();\" onMouseUp=\"this.blur();\">Filters&nbsp;<img src='https://support.bytro.com/themes/admin_default/menudrop.gif' border='0' /></a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='#' title='Reports'id='linkreportt' onClick=\"javascript:CustomPopup('reportt', event, \'linkreportt\', \'reportt\');this.blur();\" onMouseUp=\"this.blur();\">Reports&nbsp;<img src='https://support.bytro.com/themes/admin_default/menudrop.gif' border='0' /></a>";
menulinks[8] = "<a href='index.php?_m=teamwork&_a=calendar' title='Manage Calendar'>Manage Calendar</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='index.php?_m=teamwork&_a=tasks' title='Manage Tasks'>Manage Tasks</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='index.php?_m=teamwork&_a=contacts' title='Manage Contacts'>Manage Contacts</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='index.php?_m=teamwork&_a=insertcontact' title='Insert Contact'>Insert Contact</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='index.php?_m=teamwork&_a=insertevent' title='Insert Event'>Insert Event</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='index.php?_m=teamwork&_a=inserttask' title='Insert Task'>Insert Task</a>";
menulinks[9] = "<a href='index.php?_m=core&_a=manageusers' title='Manage Users'>Manage Users</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='index.php?_m=core&_a=manageusergroups' title='Manage Groups'>Manage Groups</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='index.php?_m=core&_a=insertuser' title='Insert User'>Insert User</a>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;<a href='index.php?_m=core&_a=insertusergroup' title='Insert Group'>Insert Group</a>&nbsp;&nbsp;&nbsp;&nbsp; |";
menulinks[10] = "<a href='index.php?_m=typo3users&_a=sendpmtoalist' title='Send PM to a List'>Send PM to a List</a>&nbsp;&nbsp;&nbsp;&nbsp; |";
menulinks[11] = "<a href='index.php?_m=typo3alliances&_a=listalliances' title='List Alliances'>List Alliances</a>&nbsp;&nbsp;&nbsp;&nbsp; |";

function preloadMenuImages() {
    preloadImages('https://support.bytro.com/themes/admin_default/loadingcircle.gif', 'https://support.bytro.com/themes/admin_default/menusection1.gif', 'https://support.bytro.com/themes/admin_default/menusection2.gif', 'https://support.bytro.com/themes/admin_default/menusection3.gif', 'https://support.bytro.com/themes/admin_default/menusection4.gif', 'https://support.bytro.com/themes/admin_default/menusection5.gif', 'https://support.bytro.com/themes/admin_default/menusection6.gif', 'https://support.bytro.com/themes/admin_default/menusection7.gif', 'https://support.bytro.com/themes/admin_default/menusection8.gif', 'https://support.bytro.com/themes/admin_default/menusection9.gif', 'https://support.bytro.com/themes/admin_default/menusection10.gif', 'https://support.bytro.com/themes/admin_default/tablebg.gif', 'https://support.bytro.com/themes/admin_default/tabledescbg.gif', 'https://support.bytro.com/themes/admin_default/menudrop.gif');
}
